import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { Link } from "react-router-dom";
import useAppContext from "../utils/Maincontext.js";
// Define the CategoriesHeader functional component
const CategoriesHeader = () => {
    // Use the 'useAppContext' hook to access the 'handleBtnName' and 'btnName' variables from the context
    const { handleBtnName, btnName } = useAppContext();
    return (_jsx(_Fragment, { children: _jsx("div", { className: "mx-auto max-w-[1200px] px-[19]", children: _jsxs("div", { className: "flex items-center flex-col pt-[4rem]", children: [_jsxs("div", { className: "flex items-center mb-24 w-full", children: [_jsx(Link, { onClick: () => window.scrollTo(0, 0), to: "/", className: "items-center text-black flex text-[1.6rem] justify-center text-left decoration-none", children: "< Home" }), _jsx("h3", { className: "text-[2rem] font-bold mx-auto text-center uppercase", children: btnName })] }), _jsxs("div", { className: "flex items-center flex-wrap gap-4 justify-center w-full", children: [_jsx(Link, { to: "all", onClick: () => handleBtnName("all"), className: `border-2 py-1 px-4 ${btnName === "all" ? "border-black" : "border-gray-500"} hover:border-black transition-all duration-300`, children: _jsx("button", { children: "All" }) }), _jsx(Link, { to: "furnitures", className: `border-2 py-1 px-4 ${btnName === "furnitures" ? "border-black" : "border-gray-500"} hover:border-black transition-all duration-300`, children: _jsx("button", { onClick: () => handleBtnName("furnitures"), children: "Furnitures" }) }), _jsx(Link, { to: "electronics", className: `border-2 py-1 px-4 ${btnName === "electronics" ? "border-black" : "border-gray-500"} hover:border-black transition-all duration-300`, children: _jsx("button", { onClick: () => handleBtnName("electronics"), children: "Electronics" }) }), _jsx(Link, { to: "lamp", className: `border-2 py-1 px-4 ${btnName === "lamp" ? "border-black" : "border-gray-500"} hover:border-black transition-all duration-300`, children: _jsx("button", { onClick: () => handleBtnName("lamp"), children: "Lamps" }) }), _jsx(Link, { to: "kitchen", className: `border-2 py-1 px-4 ${btnName === "kitchen" ? "border-black" : "border-gray-500"} hover:border-black transition-all duration-300`, children: _jsx("button", { onClick: () => handleBtnName("kitchen"), children: "Kitchen" }) }), _jsx(Link, { to: "chairs", className: `border-2 py-1 px-4 ${btnName === "chairs" ? "border-black" : "border-gray-500"} hover:border-black transition-all duration-300`, children: _jsx("button", { onClick: () => handleBtnName("chairs"), children: "Chairs" }) }), _jsx(Link, { to: "skin-care", className: `border-2 py-1 px-4 ${btnName === "skin care" ? "border-black" : "border-gray-500"} hover:border-black transition-all duration-300`, children: _jsx("button", { onClick: () => handleBtnName("skin care"), children: "Skin Care" }) })] })] }) }) }));
};
export default CategoriesHeader;
